[package]
edition.workspace = true
license.workspace = true
name = "katana-migration"
repository.workspace = true
version.workspace = true

[dependencies]
katana-chain-spec.workspace = true
katana-core.workspace = true
katana-db.workspace = true
katana-executor.workspace = true
katana-primitives.workspace = true
katana-provider.workspace = true

anyhow.workspace = true
similar-asserts.workspace = true
tracing.workspace = true

[dev-dependencies]
fs_extra = "1.3.0"
katana-chain-spec.workspace = true
tempfile.workspace = true
